---

- hosts: nginx
  user: root
  tasks:
  - name: copy_from_local_distr_to_nginx_config
    copy:
     src: /tmp/semaphore/repository_1/playbooks/roles/nginx/files/sites-available/
     dest: /etc/nginx/sites-available