---

- hosts: nginx
  user: root
  tasks:
  - name: copy file
    git: 
     repo: ssh://git@github.com:yazevjohn/ansible_repo.git
     dest: /tmp/git_repo_ansible
  - name: copy_from_local_distr_to_nginx_config
    copy:
     src: /tmp/git_repo_ansible/playbooks/roles/nginx/files/sites-available/
     dest: /etc/nginx/sites-available/